# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.network :private_network, ip: "10.0.0.18"
  config.vm.network :forwarded_port, guest: 80, host: 8080

  config.vm.synced_folder "..", "/project_share", type: "rsync",
      rsync__args: ["--verbose", "--archive", "-z"],
      rsync__exclude: [".git", "tools/*modules", "node_modules"]

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "puppet/manifests"
    puppet.module_path = "puppet/modules"
    puppet.manifest_file  = "init.pp"
    puppet.options="--verbose"
  end
end
